// Code generated by kanna. DO NOT EDIT.

package app

import (
	"github.com/go-kanna/kanna/examples/di/app/infra"
	"github.com/go-kanna/kanna/examples/di/app/service"
)

// NewApp initializes dependencies and constructs App.
func NewApp(deps infra.Deps, env service.Env) *App {
	db := deps.DB
	user := service.NewUser(db, env)
	notifier := service.NewLogNotifier()

	return &App{
		User:     user,
		Notifier: notifier,
	}
}

// NewGreeterService initializes dependencies and constructs greeterApp.
func NewGreeterService(env service.Env) service.Greeter {
	greeter := service.NewGreeter(env)

	return &greeterApp{
		greeter: greeter,
	}
}
