// Code generated by kanna. DO NOT EDIT.

package app_test

import (
	"github.com/go-kanna/kanna/examples/di/app"
	"github.com/go-kanna/kanna/examples/di/app/infra"
	"github.com/go-kanna/kanna/examples/di/app/service"
)

// newTestEnv initializes dependencies and constructs testEnv.
func newTestEnv(deps infra.Deps, env service.Env) *testEnv {
	application := app.NewApp(deps, env)
	db := deps.DB
	user := service.NewUser(db, env)

	return &testEnv{
		deps:        deps,
		application: application,
		user:        user,
	}
}
