BUILD_DIR = bin

# Examples regenerated by the `example` target. The MUST group is regenerated
# with --must so it also produces MustNew* constructors.
EXAMPLES_PLAIN = simple returns name-conflict embedded embed
EXAMPLES_MUST  = with-error embedded-error

.PHONY: test
test:
	go test ./... -race

.PHONY: lint
lint:
	@command -v golangci-lint >/dev/null 2>&1 || { \
		echo "golangci-lint is not installed"; \
		exit 1; \
	}
	golangci-lint run

.PHONY: lint-fix
lint-fix:
	@command -v golangci-lint >/dev/null 2>&1 || { \
		echo "golangci-lint is not installed"; \
		exit 1; \
	}
	golangci-lint run --fix

.PHONY: build
build:
	go build -o $(BUILD_DIR)/kanna-di ./cmd/kanna-di

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)

# Regenerate every example from scratch and confirm the result still builds.
# CI runs this and then checks that the working tree is unchanged, which turns
# the examples into an end-to-end regression test for the generator.
.PHONY: example
example: build
	@for ex in $(EXAMPLES_PLAIN); do \
		echo ">>> regenerate example/$$ex"; \
		(cd example && ../$(BUILD_DIR)/kanna-di ./$$ex/...) || exit 1; \
	done
	@for ex in $(EXAMPLES_MUST); do \
		echo ">>> regenerate example/$$ex --must"; \
		(cd example && ../$(BUILD_DIR)/kanna-di --must ./$$ex/...) || exit 1; \
	done
	cd example && go vet ./... && go build ./...
