BUILD_DIR = bin

# Each generator gets one example module under examples/, regenerated by the
# `examples` target.
EXAMPLES = di

.PHONY: test
test:
	go test ./... -race

.PHONY: lint
lint:
	@command -v golangci-lint >/dev/null 2>&1 || { \
		echo "golangci-lint is not installed"; \
		exit 1; \
	}
	golangci-lint run

.PHONY: lint-fix
lint-fix:
	@command -v golangci-lint >/dev/null 2>&1 || { \
		echo "golangci-lint is not installed"; \
		exit 1; \
	}
	golangci-lint run --fix

.PHONY: build
build:
	go build -o $(BUILD_DIR)/kanna-di ./cmd/kanna-di

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)

# Regenerate every example and confirm the result still builds and runs. CI runs
# this and then checks that the working tree is unchanged, which turns the
# examples into an end-to-end regression test for the generators.
#
# Generation goes through `go generate`, so what runs here is exactly the
# //go:generate line an example shows its readers. The go.work at the repository
# root is what lets the tool directive resolve to this checkout.
.PHONY: examples
examples:
	@for ex in $(EXAMPLES); do \
		echo ">>> regenerate examples/$$ex"; \
		(cd examples/$$ex && go generate ./...) || exit 1; \
		(cd examples/$$ex && go vet ./... && go build ./... && go run .) || exit 1; \
	done
