// Code generated by kanna. DO NOT EDIT.

package infra

// NewDeps initializes dependencies and constructs Deps.
func NewDeps() (*Deps, error) {
	config := NewConfig()
	db, err := NewDB(config)
	if err != nil {
		return nil, err
	}
	cache := NewCache()

	return &Deps{
		DB:    db,
		Cache: cache,
	}, nil
}

// MustNewDeps initializes dependencies and constructs Deps or panics on failure.
func MustNewDeps() *Deps {
	v, err := NewDeps()
	if err != nil {
		panic(err)
	}
	return v
}
