// Code generated by kanna. DO NOT EDIT.

package messages

import (
	"golang.org/x/text/language"

	"github.com/go-kanna/kanna/i18n"
)

// Greeting returns the "greeting" message.
func Greeting() i18n.Message {
	return i18n.Message{Key: "greeting"}
}

// Hello returns the "hello" message.
func Hello(name string) i18n.Message {
	return i18n.Message{Key: "hello", Args: []i18n.Arg{
		{Name: "name", Value: name},
	}}
}

// ItemsCount returns the "items_count" message.
func ItemsCount(count int) i18n.Message {
	return i18n.Message{Key: "items_count", Args: []i18n.Arg{
		{Name: "count", Value: count},
	}}
}

// TotalPrice returns the "total_price" message.
func TotalPrice(price float64) i18n.Message {
	return i18n.Message{Key: "total_price", Args: []i18n.Arg{
		{Name: "price", Value: price},
	}}
}

// UserDeleted returns the "user.deleted" message.
func UserDeleted(name string) i18n.Message {
	return i18n.Message{Key: "user.deleted", Args: []i18n.Arg{
		{Name: "name", Value: name},
	}}
}

// UserNotFound returns the "user.not_found" message.
func UserNotFound() i18n.Message {
	return i18n.Message{Key: "user.not_found"}
}

// Localizer renders this package's messages in the compiled locale best
// matching tag. Messages missing from the matched locale fall back to the
// default language.
func Localizer(tag language.Tag) i18n.Localizer {
	return bundle.Localizer(tag)
}

// bundle holds every locale this package was generated from.
var bundle = i18n.NewBundle("en",
	i18n.Catalog{Lang: "en", Entries: map[string]i18n.Entry{
		"greeting": {Single: i18n.Template{{Text: "Hello!"}}},
		"hello":    {Single: i18n.Template{{Text: "Hello, "}, {Param: "name"}, {Text: "!"}}},
		"items_count": {Plural: map[string]i18n.Template{
			"one":   {{Text: "You have "}, {Param: "count"}, {Text: " item."}},
			"other": {{Text: "You have "}, {Param: "count"}, {Text: " items."}},
		}},
		"total_price":    {Single: i18n.Template{{Text: "Total: "}, {Param: "price", Kind: i18n.KindNumber}}},
		"user.deleted":   {Single: i18n.Template{{Text: "User "}, {Param: "name"}, {Text: " has been deleted."}}},
		"user.not_found": {Single: i18n.Template{{Text: "User not found."}}},
	}},
	i18n.Catalog{Lang: "ja", Entries: map[string]i18n.Entry{
		"greeting": {Single: i18n.Template{{Text: "こんにちは！"}}},
		"hello":    {Single: i18n.Template{{Text: "こんにちは、"}, {Param: "name"}, {Text: "さん！"}}},
		"items_count": {Plural: map[string]i18n.Template{
			"other": {{Text: "アイテムが"}, {Param: "count"}, {Text: "個あります。"}},
		}},
		"total_price":    {Single: i18n.Template{{Text: "合計: "}, {Param: "price", Kind: i18n.KindNumber}}},
		"user.deleted":   {Single: i18n.Template{{Text: "ユーザー"}, {Param: "name"}, {Text: "を削除しました。"}}},
		"user.not_found": {Single: i18n.Template{{Text: "ユーザーが見つかりません。"}}},
	}},
)
