// Code generated by kanna. DO NOT EDIT.

package fixture

import (
	"github.com/brianvoe/gofakeit/v7"
	"github.com/google/uuid"

	"github.com/go-kanna/kanna/examples/fixture/model"
)

func Article(setters ...func(m *model.Article)) model.Article {
	m := model.Article{
		ID:          uuid.MustParse(gofakeit.UUID()),
		Slug:        mustGenerate("???-####"),
		Title:       gofakeit.Word(),
		Status:      model.Status(gofakeit.Word()),
		Author:      User(),
		PublishedAt: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func User(setters ...func(m *model.User)) model.User {
	m := model.User{
		ID:        gofakeit.Int64(),
		Name:      gofakeit.Name(),
		Email:     gofakeit.Email(),
		Age:       gofakeit.Number(18, 65),
		CreatedAt: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func mustGenerate(template string) string {
	s, err := gofakeit.Generate(template)
	if err != nil {
		panic(err)
	}
	return s
}
