// Code generated by kanna. DO NOT EDIT.

package mapper

import (
	"fmt"

	"github.com/go-kanna/kanna/examples/mapper/gen/employeev1"
	"github.com/go-kanna/kanna/examples/mapper/lib/converters"
	"github.com/go-kanna/kanna/examples/mapper/model"
	"github.com/google/uuid"
)

// EmployeeToEmployeev1 maps model.Employee to *employeev1.Employee.
func EmployeeToEmployeev1(src model.Employee) *employeev1.Employee {
	return &employeev1.Employee{
		Id:        converters.UUIDToString(src.ID),
		Name:      src.Name,
		HiredAt:   converters.ToDate(src.HiredAt),
		Address:   AddressToEmployeev1(src.Address),
		Nicknames: src.Nicknames,
	}
}

// EmployeeFromEmployeev1 maps *employeev1.Employee to model.Employee.
func EmployeeFromEmployeev1(src *employeev1.Employee) (model.Employee, error) {
	if src == nil {
		return model.Employee{}, nil
	}
	v1, err0 := uuid.Parse(src.GetId())
	if err0 != nil {
		return model.Employee{}, fmt.Errorf("map model.Employee.ID: %w", err0)
	}
	return model.Employee{
		ID:        v1,
		Name:      src.GetName(),
		HiredAt:   converters.ToTime(src.GetHiredAt()),
		Address:   AddressFromEmployeev1(src.GetAddress()),
		Nicknames: src.GetNicknames(),
	}, nil
}

// AddressToEmployeev1 maps model.Address to *employeev1.Address.
func AddressToEmployeev1(src model.Address) *employeev1.Address {
	return &employeev1.Address{
		City:   src.City,
		Street: src.Street,
	}
}

// AddressFromEmployeev1 maps *employeev1.Address to model.Address.
func AddressFromEmployeev1(src *employeev1.Address) model.Address {
	if src == nil {
		return model.Address{}
	}
	return model.Address{
		City:   src.GetCity(),
		Street: src.GetStreet(),
	}
}
