package output_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-kanna/kanna/internal/output"
)

const generated = "// Code generated by kanna. DO NOT EDIT.\n\npackage x\n"

// A license tool prepending its header must not hide the marker from us: that
// is exactly the mistake a raw prefix comparison makes.
const licensed = "// Copyright 2026 Acme Corp.\n// SPDX-License-Identifier: MIT\n\n" + generated

const constrained = "//go:build !windows\n\n" + generated

const handWritten = "package x\n\n// Written by hand.\n"

func write(t *testing.T, dir, body string) string {
	t.Helper()

	path := filepath.Join(dir, "x.go")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestResolve(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		dir  string
		path string
		want string
	}{
		{name: "relative against dir", dir: "/work", path: "out/x.go", want: "/work/out/x.go"},
		{name: "absolute passes through", dir: "/work", path: "/abs/x.go", want: "/abs/x.go"},
		{name: "empty dir passes through", dir: "", path: "out/x.go", want: "out/x.go"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if got := output.Resolve(tt.dir, tt.path); got != tt.want {
				t.Errorf("Resolve(%q, %q) = %q, want %q", tt.dir, tt.path, got, tt.want)
			}
		})
	}
}

func TestWrite(t *testing.T) {
	t.Parallel()

	t.Run("creates the directory", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "deep", "down", "x.go")
		if err := output.Write(path, []byte(generated)); err != nil {
			t.Fatalf("Write() error = %v", err)
		}
		got, err := os.ReadFile(filepath.Clean(path))
		if err != nil || string(got) != generated {
			t.Errorf("written file = %q, %v", got, err)
		}
	})

	t.Run("replaces its own output", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), generated)
		next := strings.Replace(generated, "package x", "package y", 1)
		if err := output.Write(path, []byte(next)); err != nil {
			t.Fatalf("Write() error = %v", err)
		}
	})

	t.Run("replaces its output behind a license header", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), licensed)
		if err := output.Write(path, []byte(generated)); err != nil {
			t.Errorf("Write() refused a licensed generated file: %v", err)
		}
	})

	t.Run("replaces its output behind a build constraint", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), constrained)
		if err := output.Write(path, []byte(generated)); err != nil {
			t.Errorf("Write() refused a build-constrained generated file: %v", err)
		}
	})

	t.Run("refuses a hand-written file", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), handWritten)
		err := output.Write(path, []byte(generated))
		if err == nil || !strings.Contains(err.Error(), "generated-code header") {
			t.Fatalf("Write() = %v, want a refusal naming the header", err)
		}
		got, _ := os.ReadFile(filepath.Clean(path))
		if string(got) != handWritten {
			t.Error("the hand-written file was overwritten")
		}
	})

	t.Run("identical content is left alone", func(t *testing.T) {
		t.Parallel()

		// Even a hand-written file: writing the same bytes changes nothing, so
		// there is nothing to protect.
		path := write(t, t.TempDir(), generated)
		if err := output.Write(path, []byte(generated)); err != nil {
			t.Errorf("Write() error = %v", err)
		}
	})
}

func TestCheckUpToDate(t *testing.T) {
	t.Parallel()

	t.Run("missing file", func(t *testing.T) {
		t.Parallel()

		err := output.CheckUpToDate(filepath.Join(t.TempDir(), "x.go"), []byte(generated))
		if err == nil || !strings.Contains(err.Error(), "has not been generated yet") {
			t.Errorf("CheckUpToDate() = %v, want the not-generated-yet message", err)
		}
	})

	t.Run("fresh file", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), generated)
		if err := output.CheckUpToDate(path, []byte(generated)); err != nil {
			t.Errorf("CheckUpToDate() = %v, want nil", err)
		}
	})

	t.Run("stale file", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), generated)
		next := strings.Replace(generated, "package x", "package y", 1)
		err := output.CheckUpToDate(path, []byte(next))
		if err == nil || !strings.Contains(err.Error(), "out of date") {
			t.Errorf("CheckUpToDate() = %v, want the out-of-date message", err)
		}
	})

	t.Run("hand-written file is not merely stale", func(t *testing.T) {
		t.Parallel()

		path := write(t, t.TempDir(), handWritten)
		err := output.CheckUpToDate(path, []byte(generated))
		if err == nil || !strings.Contains(err.Error(), "hand-written") {
			t.Errorf("CheckUpToDate() = %v, want the hand-written message", err)
		}
		if err != nil && strings.Contains(err.Error(), "out of date") {
			t.Errorf("CheckUpToDate() = %v, must not send the user to go generate", err)
		}
	})
}

func TestPackageName(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		override string
		dir      string
		// files, when non-nil, are written into the destination directory;
		// a nil map leaves the directory missing.
		files   map[string]string
		want    string
		wantErr bool
	}{
		{
			// Overriding to the name already declared is redundant but harmless.
			name:     "override agreeing with the declared package",
			override: "fixture",
			dir:      "fixture",
			files:    map[string]string{"fixture.go": "package fixture\n"},
			want:     "fixture",
		},
		{
			// Every file in a directory has to agree on the package clause, so
			// this cannot be honored: it would produce a file that does not
			// compile next to the one already there.
			name:     "override conflicting with the declared package",
			override: "fx",
			dir:      "fixture",
			files:    map[string]string{"fixture.go": "package fixture\n"},
			wantErr:  true,
		},
		{
			// With nothing declared yet there is nothing to conflict with.
			name:     "override in an empty directory",
			override: "fx",
			dir:      "fixture",
			want:     "fx",
		},
		{
			name:  "declared package wins over the directory name",
			dir:   "fixtures",
			files: map[string]string{"employee_fixture.go": "package fixture\n"},
			want:  "fixture",
		},
		{
			name:  "a previously generated file does not pin the name",
			dir:   "fixture",
			files: map[string]string{"fixture_gen.go": "package stale\n"},
			want:  "fixture",
		},
		{
			name:  "external test files are ignored",
			dir:   "fixture",
			files: map[string]string{"fixture_test.go": "package fixture_test\n"},
			want:  "fixture",
		},
		{
			name: "a missing directory falls back to its name",
			dir:  "fixture",
			want: "fixture",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			dest := filepath.Join(t.TempDir(), tt.dir)

			if tt.files != nil {
				if err := os.MkdirAll(dest, 0o750); err != nil {
					t.Fatalf("mkdir: %v", err)
				}

				for name, body := range tt.files {
					if err := os.WriteFile(filepath.Join(dest, name), []byte(body), 0o600); err != nil {
						t.Fatalf("write %s: %v", name, err)
					}
				}
			}

			got, err := output.PackageName(tt.override, dest, "fixture_gen.go")
			if tt.wantErr {
				if err == nil {
					t.Fatalf("PackageName(%q, %q) = %q, want an error", tt.override, dest, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("PackageName(%q, %q) error = %v", tt.override, dest, err)
			}
			if got != tt.want {
				t.Errorf("PackageName(%q, %q) = %q, want %q", tt.override, dest, got, tt.want)
			}
		})
	}
}
