package scan_test

import (
	"go/parser"
	"go/token"
	"slices"
	"testing"

	"github.com/go-kanna/kanna/internal/diag"
	"github.com/go-kanna/kanna/internal/internaltest"
	"github.com/go-kanna/kanna/internal/ir"
	"github.com/go-kanna/kanna/internal/packages"
	"github.com/go-kanna/kanna/internal/scan"
)

func TestStructs_ReportsUnexportedTypesAndFields(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Exported struct {
	Public  string
	private int
}

type unexported struct {
	Public string
}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	if got, want := structNames(structs), []string{"Exported", "unexported"}; !slices.Equal(got, want) {
		t.Fatalf("structs = %v, want %v", got, want)
	}

	fields := structs[0].Fields
	if got, want := len(fields), 2; got != want {
		t.Fatalf("Exported fields = %d, want %d", got, want)
	}
	if fields[0].Name != "Public" || !fields[0].Exported {
		t.Errorf("field 0 = %+v, want exported Public", fields[0])
	}
	if fields[1].Name != "private" || fields[1].Exported {
		t.Errorf("field 1 = %+v, want unexported private", fields[1])
	}
}

func TestStructs_PreservesDeclarationOrder(t *testing.T) {
	t.Parallel()

	// Declared in reverse alphabetical order to prove the result is not simply
	// the alphabetically sorted output of types.Scope.Names.
	pkg := internaltest.LoadFile(t, `package test

type Zebra struct{}
type Mango struct{}
type Apple struct{}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	if got, want := structNames(structs), []string{"Zebra", "Mango", "Apple"}; !slices.Equal(got, want) {
		t.Errorf("structs = %v, want declaration order %v", got, want)
	}
}

func TestStructs_PreservesFieldOrder(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Row struct {
	Zebra string
	Apple string
	Mango string
}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	names := make([]string, 0, len(structs[0].Fields))
	for _, f := range structs[0].Fields {
		names = append(names, f.Name)
	}
	if want := []string{"Zebra", "Apple", "Mango"}; !slices.Equal(names, want) {
		t.Errorf("fields = %v, want %v", names, want)
	}
}

func TestStructs_ReportsEmbeddedFields(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Base struct {
	ID string
}

type Child struct {
	Base
	Name string
}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	child := findStruct(t, structs, "Child")
	if got, want := len(child.Fields), 2; got != want {
		t.Fatalf("Child fields = %d, want %d", got, want)
	}

	embedded := child.Fields[0]
	if !embedded.Embedded {
		t.Errorf("field 0 Embedded = false, want true")
	}
	if embedded.Name != "Base" {
		t.Errorf("field 0 Name = %q, want %q (the embedded type name)", embedded.Name, "Base")
	}
	if child.Fields[1].Embedded {
		t.Errorf("field 1 Embedded = true, want false")
	}
}

func TestStructs_ReportsTags(t *testing.T) {
	t.Parallel()

	src := `package test

type Row struct {
	Name string ` + "`json:\"name\" orm:\"column=name\"`" + `
	Skip string
}
`
	pkg := internaltest.LoadFile(t, src)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	fields := structs[0].Fields
	if got, ok := fields[0].Tag.Lookup("orm"); !ok || got != "column=name" {
		t.Errorf(`Tag.Lookup("orm") = %q, %v; want %q, true`, got, ok, "column=name")
	}
	if got, ok := fields[0].Tag.Lookup("json"); !ok || got != "name" {
		t.Errorf(`Tag.Lookup("json") = %q, %v; want %q, true`, got, ok, "name")
	}
	if _, ok := fields[1].Tag.Lookup("orm"); ok {
		t.Error("untagged field reported a tag value")
	}
}

func TestStructs_ReportsGenericStructs(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Box[T any] struct {
	Value T
}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	box := findStruct(t, structs, "Box")
	if got := box.Named.TypeParams().Len(); got != 1 {
		t.Errorf("TypeParams().Len() = %d, want 1", got)
	}
}

func TestStructs_ExcludesAliasesAndNonStructTypes(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Real struct{}

type Alias = Real

type Count int

type Handler func() error

type Reader interface{ Read() error }
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	if got, want := structNames(structs), []string{"Real"}; !slices.Equal(got, want) {
		t.Errorf("structs = %v, want %v", got, want)
	}
}

func TestStructs_SkipsGeneratedFiles(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadPackage(t, map[string]string{
		"a_handwritten.go": `package test

type Handwritten struct{}
`,
		"b_generated.go": `// Code generated by kanna. DO NOT EDIT.

package test

type Generated struct{}
`,
	})

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	if got, want := structNames(structs), []string{"Handwritten"}; !slices.Equal(got, want) {
		t.Errorf("structs = %v, want %v", got, want)
	}
}

func TestStructs_CollectsDocComments(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

// Documented is a struct with its own doc comment.
//kanna:something
type Documented struct{}

// Grouped documents the whole declaration.
type (
	Inherited struct{}
)

type Undocumented struct{}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	documented := findStruct(t, structs, "Documented")
	if want := []string{
		"// Documented is a struct with its own doc comment.",
		"//kanna:something",
	}; !slices.Equal(documented.Doc, want) {
		t.Errorf("Documented.Doc = %q, want %q", documented.Doc, want)
	}

	// A GenDecl comment stands in when the TypeSpec has none.
	inherited := findStruct(t, structs, "Inherited")
	if want := []string{"// Grouped documents the whole declaration."}; !slices.Equal(inherited.Doc, want) {
		t.Errorf("Inherited.Doc = %q, want %q", inherited.Doc, want)
	}

	if got := findStruct(t, structs, "Undocumented").Doc; len(got) != 0 {
		t.Errorf("Undocumented.Doc = %q, want empty", got)
	}
}

func TestStructs_ReportsPackageMetadata(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Row struct{}
`)

	structs, ds := scan.Structs([]*packages.Package{pkg})
	assertNoErrors(t, ds)

	s := structs[0]
	if s.PkgPath != "test" || s.PkgName != "test" {
		t.Errorf("PkgPath, PkgName = %q, %q; want %q, %q", s.PkgPath, s.PkgName, "test", "test")
	}
	if s.Pos.Filename != "test.go" {
		t.Errorf("Pos.Filename = %q, want %q", s.Pos.Filename, "test.go")
	}
}

func TestStructs_SkipsNilPackages(t *testing.T) {
	t.Parallel()

	structs, ds := scan.Structs([]*packages.Package{nil})
	assertNoErrors(t, ds)

	if len(structs) != 0 {
		t.Errorf("structs = %v, want empty", structNames(structs))
	}
}

func TestStructs_ReportsMissingTypeInformation(t *testing.T) {
	t.Parallel()

	structs, ds := scan.Structs([]*packages.Package{{PkgPath: "broken"}})

	if !diag.HasErrors(ds) {
		t.Fatal("Structs() reported no error for a package without type information")
	}
	if len(structs) != 0 {
		t.Errorf("structs = %v, want empty", structNames(structs))
	}
}

func TestStructs_ReportsLoadErrors(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Row struct{}
`)
	pkg.Errors = []packages.Error{{Msg: "some load failure"}}

	structs, ds := scan.Structs([]*packages.Package{pkg})

	if !diag.HasErrors(ds) {
		t.Fatal("Structs() did not surface pkg.Errors as diagnostics")
	}
	// Structs that still resolved are returned so callers can report as much as
	// possible before bailing out.
	if got, want := structNames(structs), []string{"Row"}; !slices.Equal(got, want) {
		t.Errorf("structs = %v, want %v", got, want)
	}
}

func TestIsGenerated(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "canonical marker",
			src:  "// Code generated by kanna. DO NOT EDIT.\n\npackage test\n",
			want: true,
		},
		{
			name: "marker among leading comments",
			src:  "// Copyright 2026\n// Code generated by kanna. DO NOT EDIT.\n\npackage test\n",
			want: true,
		},
		{
			name: "no comment",
			src:  "package test\n",
			want: false,
		},
		{
			name: "unrelated comment",
			src:  "// Package test does things.\npackage test\n",
			want: false,
		},
		{
			name: "marker after package clause does not count",
			src:  "package test\n\n// Code generated by kanna. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "missing trailing period",
			src:  "// Code generated by kanna. DO NOT EDIT\n\npackage test\n",
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, "test.go", tt.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if got := scan.IsGenerated(file); got != tt.want {
				t.Errorf("IsGenerated() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestIsGenerated_NilFile(t *testing.T) {
	t.Parallel()

	if scan.IsGenerated(nil) {
		t.Error("IsGenerated(nil) = true, want false")
	}
}

func TestResolveTypeExpr(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

type Row struct{}
`)

	got, err := scan.ResolveTypeExpr(pkg, "*Row")
	if err != nil {
		t.Fatalf("ResolveTypeExpr: %v", err)
	}
	if want := "*test.Row"; got.String() != want {
		t.Errorf("ResolveTypeExpr() = %q, want %q", got.String(), want)
	}
}

func TestResolveTypeExpr_Errors(t *testing.T) {
	t.Parallel()

	pkg := internaltest.LoadFile(t, `package test

const Answer = 42

type Row struct{}
`)

	tests := []struct {
		name string
		expr string
	}{
		{name: "undefined name", expr: "Missing"},
		{name: "not a type", expr: "Answer"},
		{name: "malformed", expr: "*"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if _, err := scan.ResolveTypeExpr(pkg, tt.expr); err == nil {
				t.Errorf("ResolveTypeExpr(%q) returned nil error", tt.expr)
			}
		})
	}
}

func TestResolveTypeExpr_MissingTypeInformation(t *testing.T) {
	t.Parallel()

	if _, err := scan.ResolveTypeExpr(&packages.Package{}, "int"); err == nil {
		t.Error("ResolveTypeExpr() returned nil error for a package without type information")
	}
}

func structNames(structs []ir.Struct) []string {
	names := make([]string, 0, len(structs))
	for _, s := range structs {
		names = append(names, s.Name)
	}
	return names
}

func findStruct(t *testing.T, structs []ir.Struct, name string) ir.Struct {
	t.Helper()

	for _, s := range structs {
		if s.Name == name {
			return s
		}
	}
	t.Fatalf("struct %q not found in %v", name, structNames(structs))
	return ir.Struct{}
}

func assertNoErrors(t *testing.T, ds []diag.Diag) {
	t.Helper()

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diagnostics: %s", diag.Format(ds))
	}
}
